Adding Hover effect
anmode/grabtern-frontend pull request #158
Opened 2023-05-27 07:19 UTC by shwetazade27

## Related Issue
#120 

## Description of Changes

Added hovering effect on navbar tabs 

## Screenshots
original:
![old_one](https://github.com/anmode/grabtern-frontend/assets/84389800/9615300e-3869-4f19-9a96-57bbc0f5a970)
updated:
![new_one](https://github.com/anmode/grabtern-frontend/assets/84389800/39c280a1-473c-48aa-b177-0011504f3cd0)

2023-05-27 09:31 UTC, anmode commented
please update your pR. fetch the latest changes.

2023-05-27 10:32 UTC, shwetazade27 commented
@anmode sir please help me with this one how to update pr

2023-05-27 11:23 UTC, anmode commented
follow the steps:
1. Checkout the develop branch ( `git checkout develop`)
2. Pull the latest changes ( `git pull` )
3. try one more time `git fetch`
make sure your remote (your github repo) is upto date with usptream(my github repo)
4. checkout to your feature branch (`git checkout your_branch`)
5. `git merge develop`

2023-05-27 12:01 UTC, shwetazade27 commented
Done sir... @anmode 
![updated](https://github.com/anmode/grabtern-frontend/assets/84389800/b12d9818-5a06-491a-a1bf-6eb99bc62997)

2023-05-27 12:43 UTC, anmode commented
great!

2023-05-27 12:44 UTC, anmode requested changes
One more things please see and optimize for mobile too!

2023-05-27 12:44 UTC, anmode commented on styles/LoginDropdown.module.css
> +}
Tbh I do not like the hover...please check out https://www.amupedia.com/. see hover effect

2023-05-27 13:02 UTC, anmode commented
I did not like the color...btw can you also change the footer hyperlink...UI. As of now line is coming we can have any effect

2023-05-27 20:20 UTC, shwetazade27 commented
@anmode sir I have made bit changes in color and in  footer links please let me know if further changes or improvement is needed

2023-05-28 11:45 UTC, anmode commented
> @anmode sir I have made bit changes in color and in footer links please let me know if further changes or improvement is needed

Shweta...One thing you can do.. Just made it like...when we hover it glows. is that ok? after this change I'll merge thanks

2023-05-28 17:27 UTC, shwetazade27 commented
@anmode done.. please let me know if changes or improvement is needed.

2023-05-28 23:35 UTC, anmode commented
It should not glow initially! Make it like login button but afterward on hover it should glow

2023-05-28 23:36 UTC, anmode commented
See in production as of now www.grabtern.com now by hovering it should glow that it is!!

2023-05-29 04:52 UTC, shwetazade27 commented
@anmode done the changes, please let me know if further change is required. Thanks!

2023-05-29 08:26 UTC, anmode approved these changes
great! just run now `npx prettier --write .`

2023-05-29 11:24 UTC, shwetazade27 commented
@anmode done

2023-05-30 04:14 UTC, merged

2023-05-30 04:15 UTC, anmode commented
congrats @shwetazade27