greetings action
anmode/grabtern-frontend pull request #170
Opened 2023-05-27 13:45 UTC by Tushar98644

fixes #163

2023-05-27 13:53 UTC, anmode requested changes
We should also take into account other scenarios, such as when a mentor or collaborator creates an issue. Additionally, if a contributor who has previously created issues submits a new one, they should receive a different kind of greeting compared to a first-time contributor.

Collaborator differenly and owner differently!

2023-05-27 16:57 UTC, Tushar98644 commented
> We should also take into account other scenarios, such as when a mentor or collaborator creates an issue. Additionally, if a contributor who has previously created issues submits a new one, they should receive a different kind of greeting compared to a first-time contributor.
> 
> Collaborator differenly and owner differently!

updated , let me know if need further changes

2023-05-28 02:19 UTC, anmode requested changes
Looks cool!

2023-05-28 02:19 UTC, anmode commented on .github/workflows/greetings.yml
> +            returningContributor: "Welcome back, returning contributor! Your continued contributions are greatly appreciated!",
I think there is scope for improvement in the message. See i Don't think they are ok. and also greeting way would be different....We should write hello firstTimeContributor... instead the name but we have to greet as they comes for the first. I hope you get the point

2023-05-29 11:43 UTC, anmode commented
@Tushar98644 ?

2023-05-29 11:50 UTC, Tushar98644 commented
> @Tushar98644 ?

will update by tonight

2023-05-31 03:14 UTC, anmode commented
@Tushar98644 ?

2023-05-31 10:29 UTC, Tushar98644 commented
> @Tushar98644 ?

sorry i was stuck on some other things , i am resumed working on it .....expect an update by midnight

2023-06-01 14:06 UTC, anmode commented
hey? I think I should close it now.

2023-06-02 10:30 UTC, closed without merging