Break the changes to modular.css
anmode/grabtern-frontend pull request #224
Opened 2023-06-01 17:39 UTC by Vidip-Ghosh

## Related Issue
Broken down the changes of globals.css to modular.css

Closes: #194 

## Description of Changes

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![Original screenshot](link) | ![Updated screenshot](link) |

Please provide any necessary screenshots to illustrate the changes made.

2023-06-02 04:08 UTC, Riyazul555 commented
Please resolve conflicts and check vercel deployment

2023-06-02 04:17 UTC, Illaf approved these changes

2023-06-02 04:18 UTC, anmode requested changes
Nice changes! Well done... But yess Needs more refactoring.. Some class names are not good. Please see needs more modularity and change the class name so it is understandable what does it do

2023-06-02 04:18 UTC, anmode commented on styles/mentors.module.css
> +.mentorForm div {
This file should be further divided.... MentorRegistrationForm , MentorCard. Actually this things is each component should target particular css file.       For a case as we know there is header component so there will be header.css

2023-06-02 04:18 UTC, anmode commented on styles/Properties.module.css
> +.loaderBackground {
This file also needed to break

2023-06-02 04:20 UTC, Vidip-Ghosh commented
> Nice changes! Well done... But yess Needs more refactoring.. Some class names are not good. Please see needs more modularity and change the class name so it is understandable what does it do

Okay alright. I will make the changes

2023-06-02 04:29 UTC, Riyazul555 approved these changes
Seems fine to me except the upper changes

2023-06-03 04:54 UTC, muhammadjufry approved these changes
All are looking good, only deployment error left

2023-06-03 05:08 UTC, anmode commented
There is an error! I checked on local many CSS properties altered. I am worry!!

2023-06-03 07:39 UTC, Abhinavcode13 commented
deployment shows error here @anmode is it?

2023-08-20 13:21 UTC, closed without merging