Made CSS Modular for MentorLogin.page.js
anmode/grabtern-frontend pull request #254
Opened 2023-06-05 05:19 UTC by Sage-2001

## Related Issue

Closes: #236 

## Description of Changes
- Created a separate CSS file named MentorLogin.css
- Redesigned the CSS and added some good properties.
- Kept the classes names meaningful

## Checklist:
- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Before
![Desktop Screenshot 2023 06 05 - 10 38 53 32 (2)](https://github.com/anmode/grabtern-frontend/assets/59249586/2db395ce-5b36-4f93-aedb-df540ea14263)

After
![Desktop Screenshot 2023 06 05 - 10 41 16 67 (2)](https://github.com/anmode/grabtern-frontend/assets/59249586/266aa285-7a0a-45e1-9020-fd1b069e97ba)

2023-06-05 06:18 UTC, anmode approved these changes
looks great. Could you improve the UI too? i

2023-06-05 08:15 UTC, anmode commented
> > looks great. Could you improve the UI too? i
> 
> can you tell me what exactly needs to be improved on UI section

see user login page! I think may be similar

2023-06-06 05:15 UTC, Sage-2001 commented
> > > looks great. Could you improve the UI too? i
> > 
> > 
> > can you tell me what exactly needs to be improved on UI section
> 
> see user login page! I think may be similar

![Desktop Screenshot 2023 06 06 - 10 44 53 33](https://github.com/anmode/grabtern-frontend/assets/59249586/b102003f-381b-443a-90ce-5fa9a2396ec6)

Updated UI

2023-06-06 10:23 UTC, anmode commented
> > > > looks great. Could you improve the UI too? i
> > > 
> > > 
> > > can you tell me what exactly needs to be improved on UI section
> > 
> > 
> > see user login page! I think may be similar
> 
> ![Desktop Screenshot 2023 06 06 - 10 44 53 33](https://user-images.githubusercontent.com/59249586/243552980-b102003f-381b-443a-90ce-5fa9a2396ec6.png)
> 
> Updated UI

feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!

2023-06-06 11:42 UTC, Sage-2001 commented
> > > > > looks great. Could you improve the UI too? i
> > > > 
> > > > 
> > > > can you tell me what exactly needs to be improved on UI section
> > > 
> > > 
> > > see user login page! I think may be similar
> > 
> > 
> > ![Desktop Screenshot 2023 06 06 - 10 44 53 33](https://user-images.githubusercontent.com/59249586/243552980-b102003f-381b-443a-90ce-5fa9a2396ec6.png)
> > Updated UI
> 
> feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!

Actually yes, I tried to copy the same functionalities 

> > > > > looks great. Could you improve the UI too? i
> > > > 
> > > > 
> > > > can you tell me what exactly needs to be improved on UI section
> > > 
> > > 
> > > see user login page! I think may be similar
> > 
> > 
> > ![Desktop Screenshot 2023 06 06 - 10 44 53 33](https://user-images.githubusercontent.com/59249586/243552980-b102003f-381b-443a-90ce-5fa9a2396ec6.png)
> > Updated UI
> 
> feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!

I understand your concerns about the previous design and styling of the prototype, and I apologize for any inconvenience it may have caused. I attempted to incorporate similar functionalities to avoid any awkwardness, but I now realize that it may not have aligned with the level of professionalism I strive for. I have since made significant changes and enhancements to the prototype, focusing on creating a more visually appealing and seamless user experience. I hope that these improvements address your expectations and demonstrate my commitment to delivering a high-quality product. Thank you for your understanding, and please let me know if you have any further feedback or suggestions.

![Desktop Screenshot 2023 06 06 - 17 07 19 52](https://github.com/anmode/grabtern-frontend/assets/59249586/6c9cab71-b5bf-4f3e-9744-ea15f4651d46)

2023-06-07 02:41 UTC, anmode commented
> > feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!
> 
> I understand your concerns about the previous design and styling of the prototype, and I apologize for any inconvenience it may have caused. I attempted to incorporate similar functionalities to avoid any awkwardness, but I now realize that it may not have aligned with the level of professionalism I strive for. I have since made significant changes and enhancements to the prototype, focusing on creating a more visually appealing and seamless user experience. I hope that these improvements address your expectations and demonstrate my commitment to delivering a high-quality product. Thank you for your understanding, and please let me know if you have any further feedback or suggestions.
> 
> ![Desktop Screenshot 2023 06 06 - 17 07 19 52](https://user-images.githubusercontent.com/59249586/243682537-6c9cab71-b5bf-4f3e-9744-ea15f4651d46.png)

oh no worries! but please could you make changes to previous form? I mean it is ok you used login UI but just add fields confirm password and other option. ( as there is original mentor login).
if any query feel free to ask!!

2023-06-07 03:35 UTC, Sage-2001 commented
> > > feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!
> > 
> > 
> > I understand your concerns about the previous design and styling of the prototype, and I apologize for any inconvenience it may have caused. I attempted to incorporate similar functionalities to avoid any awkwardness, but I now realize that it may not have aligned with the level of professionalism I strive for. I have since made significant changes and enhancements to the prototype, focusing on creating a more visually appealing and seamless user experience. I hope that these improvements address your expectations and demonstrate my commitment to delivering a high-quality product. Thank you for your understanding, and please let me know if you have any further feedback or suggestions.
> > ![Desktop Screenshot 2023 06 06 - 17 07 19 52](https://user-images.githubusercontent.com/59249586/243682537-6c9cab71-b5bf-4f3e-9744-ea15f4651d46.png)
> 
> oh no worries! but please could you make changes to previous form? I mean it is ok you used login UI but just add fields confirm password and other option. ( as there is original mentor login). if any query feel free to ask!!

@anmode what do you mean by previous UI? Do you mean the original mentor form? if yes then Every field that was present in the original login form is present in the current login form.

Original form 
https://user-images.githubusercontent.com/59249586/243257539-266aa285-7a0a-45e1-9020-fd1b069e97ba.png

New form 
https://user-images.githubusercontent.com/59249586/243682537-6c9cab71-b5bf-4f3e-9744-ea15f4651d46.png

If there is something that I missed please let me know, Thanks.

2023-06-07 15:57 UTC, Sage-2001 commented
> > > > > feel's like You copied the Login Form. as `confirmPassword`? and other form fields. too please see!
> > > > 
> > > > 
> > > > I understand your concerns about the previous design and styling of the prototype, and I apologize for any inconvenience it may have caused. I attempted to incorporate similar functionalities to avoid any awkwardness, but I now realize that it may not have aligned with the level of professionalism I strive for. I have since made significant changes and enhancements to the prototype, focusing on creating a more visually appealing and seamless user experience. I hope that these improvements address your expectations and demonstrate my commitment to delivering a high-quality product. Thank you for your understanding, and please let me know if you have any further feedback or suggestions.
> > > > ![Desktop Screenshot 2023 06 06 - 17 07 19 52](https://user-images.githubusercontent.com/59249586/243682537-6c9cab71-b5bf-4f3e-9744-ea15f4651d46.png)
> > > 
> > > 
> > > oh no worries! but please could you make changes to previous form? I mean it is ok you used login UI but just add fields confirm password and other option. ( as there is original mentor login). if any query feel free to ask!!
> > 
> > 
> > @anmode what do you mean by previous UI? Do you mean the original mentor form? if yes then Every field that was present in the original login form is present in the current login form.
> > Original form https://user-images.githubusercontent.com/59249586/243257539-266aa285-7a0a-45e1-9020-fd1b069e97ba.png
> > New form https://user-images.githubusercontent.com/59249586/243682537-6c9cab71-b5bf-4f3e-9744-ea15f4651d46.png
> > If there is something that I missed please let me know, Thanks.
> 
> so the previous UI is this : https://user-images.githubusercontent.com/59249586/243552980-b102003f-381b-443a-90ce-5fa9a2396ec6.png as so use this and make sure to adjust it to have confirm passwors and other option which were in original form. I hope you get that

Done @anmode 
![Desktop Screenshot 2023 06 07 - 21 26 33 99](https://github.com/anmode/grabtern-frontend/assets/59249586/bb972c3e-f199-4614-93bc-bacdbd20677d)

2023-06-08 16:51 UTC, anmode requested changes
Cool, remove that suit png and use our png. that we have used in login page. 
@sayyedarib need your review lastly
LGTM

2023-06-08 16:55 UTC, Sage-2001 commented
> Cool, remove that suit png and use our png. that we have used in login page. @sayyedarib need your review lastly LGTM

Done @anmode 
![Desktop Screenshot 2023 06 08 - 22 24 59 85](https://github.com/anmode/grabtern-frontend/assets/59249586/91f9fe97-29fb-4f8c-acb7-a8cb55835217)

2023-06-09 03:49 UTC, Sage-2001 commented
> Change spelling of forget to forgot. And align it to left

The spelling is already forgot. Now I have aligned forgot password to the left
![Desktop Screenshot 2023 06 09 - 09 19 01 82](https://github.com/anmode/grabtern-frontend/assets/59249586/56950e71-3454-4ff8-be3f-4462d4fd697a)

2023-06-10 13:37 UTC, sayyedarib approved these changes
see the comment on line 91.

2023-06-10 14:44 UTC, Sage-2001 commented on pages/mentorLogin.page.js
> +          action="login-bg.mp4"
> see the comment on line 91. also fix formatting issue 😶

removed unnecessary stuff from the code + formatting using prettier is working fine on my local machine

2023-06-10 14:44 UTC, Sage-2001 commented
> see the comment on line 91. also fix formatting issue 😶

removed unnecessary stuff from the code + formatting using prettier is working fine on my local machine

2023-06-10 14:45 UTC, Sage-2001 commented
> > see the comment on line 91. also fix formatting issue 😶
> 
> removed unnecessary stuff from the code + Now formatting using prettier is working fine on my local machine

2023-06-10 17:13 UTC, Sage-2001 commented
> > > see the comment on line 91. also fix formatting issue 😶
> > 
> > 
> > removed unnecessary stuff from the code

2023-06-10 17:14 UTC, Sage-2001 commented
> > > > see the comment on line 91. also fix formatting issue 😶
> > > 
> > > 
> > > removed unnecessary stuff from the code



> > > > see the comment on line 91. also fix formatting issue 😶
> > > 
> > > 
> > > removed unnecessary stuff from the code + I tried running prettier locally on code it worked all right over there

2023-06-10 17:21 UTC, sayyedarib approved these changes

2023-06-11 06:28 UTC, anmode approved these changes
congrats @Sage-2001.... LGTM

2023-06-11 06:28 UTC, merged

2023-06-11 06:48 UTC, Sage-2001 commented
> congrats @Sage-2001.... LGTM

Thanks it was fun working with you @anmode and @sayyedarib