[Featurev]Added 404 error page.
anmode/grabtern-frontend pull request #286
Opened 2023-06-07 05:25 UTC by Deepanshu0703

## Related Issue

It is a 404 error page

Closes: #172

## Description of Changes

No change in the existing code just added few things

 -modified:   public/assets/css/style.css
 -Added :      components/Error.js
 -Added  :       pages/404.page.js
 -Added   :    public/assets/img/hero/download.png

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![Original screenshot]
![image](https://github.com/anmode/grabtern-frontend/assets/114489502/a83204e3-c5f2-4ca5-a908-441b532589dc) | ![Updated screenshot]![image](https://github.com/anmode/grabtern-frontend/assets/114489502/d27396e3-1811-436c-b1ac-a1408668249f)|

Please provide any necessary screenshots to illustrate the changes made.

2023-06-07 05:33 UTC, anmode commented
You can keep white background... and optimize it

2023-06-07 05:33 UTC, anmode commented
we are using this color `#845ec2`. make sure to setup theme button color and on click just make it little dark.

2023-06-07 05:39 UTC, Deepanshu0703 commented
i have used this image 
![image](https://github.com/anmode/grabtern-frontend/assets/114489502/ab2b06d0-3b47-4328-ac4f-290ee2391ddf)
 and the background is this 

![image](https://github.com/anmode/grabtern-frontend/assets/114489502/4439bf37-c3f3-43ac-9904-f1e10a3cf3cf)

and used the same button color that home page is with same hovering effect so do i have to change the color

2023-06-07 06:29 UTC, anmode commented
please do not that image.. not look great for 404 page. tagging @AmanJain18 for more details.

2023-06-07 14:42 UTC, Deepanshu0703 commented
I provided some example where he selected this so i implemented this one
Still if there is any change required I will do it . So please suggest the change @AmanJain18

2023-06-09 02:58 UTC, anmode commented
@Deepanshu0703 could you look at design.. a simple white shade (Not proper white) background with nice vector works

2023-06-09 07:25 UTC, Deepanshu0703 commented
I saw this animation may i use this one @anmode 

![Screenshot (28)](https://github.com/anmode/grabtern-frontend/assets/114489502/fe315cd4-d0c7-4df9-8be1-829dd9e4b453)

2023-06-09 07:48 UTC, Deepanshu0703 commented
Or this one , this is also an animation.

![image](https://github.com/anmode/grabtern-frontend/assets/114489502/cf4c2de2-fe96-4d13-8de8-7f3a8bed8e04)

2023-06-10 04:50 UTC, anmode commented
Think in the terms of Grabtern:
Idea - Connecting mentor and mentee ( 1-1 On mentorship)
so how would like 404 page would look like
@AmanJain18 @MohitGupta121 @Abhinavcode13  any ideas you wanna provide? or any suggestions

2023-06-10 04:56 UTC, Abhinavcode13 commented
![image](https://github.com/anmode/grabtern-frontend/assets/126642111/b44ebf90-6400-4dc8-b93e-a3e97445c3e4)
somewhat like this @anmode

2023-06-10 07:07 UTC, anmode commented
> ![image](https://user-images.githubusercontent.com/126642111/244848092-b44ebf90-6400-4dc8-b93e-a3e97445c3e4.png) somewhat like this @anmode

yeah! It's cool @Abhinavcode13

2023-06-10 08:05 UTC, Deepanshu0703 commented
Updated with the new image in the left and some description and back to homepage option in the right side

2023-06-10 11:01 UTC, MohitGupta121 commented
> > ![image](https://user-images.githubusercontent.com/126642111/244848092-b44ebf90-6400-4dc8-b93e-a3e97445c3e4.png) somewhat like this @anmode
> 
> yeah! It's cool @Abhinavcode13

@anmode This looks good to me.

2023-06-10 15:43 UTC, AmanJain18 commented
![404](https://github.com/anmode/grabtern-frontend/assets/89217032/5009a7a2-4d91-48a3-9950-2e55c9df8129)
ig this will be good ? @anmode

2023-06-10 17:38 UTC, anmode commented
> ![404](https://user-images.githubusercontent.com/89217032/244879940-5009a7a2-4d91-48a3-9950-2e55c9df8129.png) ig this will be good ? @anmode

unstop pr acha lagega....unki site ke hisab. see ek baarr

2023-06-12 09:09 UTC, Deepanshu0703 commented
I have updated the error page with this image  in the left and back to home option in left 

![image](https://github.com/anmode/grabtern-frontend/assets/114489502/39f14ce0-9ebd-4017-ad8c-cd0c8a616cd2)

2023-06-12 09:10 UTC, anmode approved these changes
Our theme color new is `#845ec2`
Remember background should not be pure white* See the new theme
https://doctor-ruby.vercel.app/. ( keep the light mode)
and 
keep the css file in style folder with name 404.css 
Btw it looks cool!

2023-06-12 09:13 UTC, Deepanshu0703 commented
here is the screenshot

![image](https://github.com/anmode/grabtern-frontend/assets/114489502/0fedd6cc-f6bb-47e9-98ac-429282c7339e)

2023-06-12 09:46 UTC, MohitGupta121 approved these changes
@Deepanshu0703 screenshot LGTM, Thanks.

2023-06-12 10:52 UTC, anmode requested changes
1. png should in webp
2. Please Use our theme color in button and try to see if you can modify image to in that color
3. why 404 not coming when i does `grabtern\ddfjd` but when i did `grabtern\sdf\dfd` it was fine

2023-06-12 10:52 UTC, anmode commented on public/assets/css/style.css
> +  display: flex;
Move the css file to `styles/404.css`

2023-06-16 07:50 UTC, anmode commented
@Deepanshu0703 ?

2023-07-22 07:03 UTC, closed without merging