implement card ui
anmode/grabtern-frontend pull request #426
Opened 2023-06-23 15:13 UTC by SVyusti

## Related Issue

 Implement Card Component for Internships 

Closes: #416

- Added a card component for featuring internships using material UI and fixed text overflow.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.
![Screenshot from 2023-06-23 20-41-20](https://github.com/anmode/grabtern-frontend/assets/101053307/40525995-ab43-4858-8495-33e37be7c268)
![Screenshot from 2023-06-23 20-41-35](https://github.com/anmode/grabtern-frontend/assets/101053307/500756a4-a5d9-4aeb-9a90-74cc9eec74e6)

2023-06-23 17:10 UTC, anmode requested changes
we have tailwind! 
please avoid using material UI

2023-06-23 19:38 UTC, SVyusti commented
Can i use nextui-org for card

On Fri, 23 Jun 2023 at 10:40 PM, Anmol Agrawal ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> we have tailwind!
> please avoid using material UI
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/anmode/grabtern-frontend/pull/426#pullrequestreview-1495529714>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYC7G6ZP2OTLFMBSYY44CGLXMXEXPANCNFSM6AAAAAAZRWKFNM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-24 02:39 UTC, anmode commented
@SVyusti The thing is we want to have optimized card... we have card component you can improve the card by using tailwind css.

No worries take your time I will email back that you have contributed to amupedia and created some issues in grabtern and also raised a PR.

2023-06-24 03:22 UTC, SVyusti commented
Thank you, 
Pls review changes.

2023-06-24 09:52 UTC, anmode requested changes
Thanks left some reviews!
But what i noticed.. carousel is not behaving properly here how you can test:
 see production one and your preview
2. Card image takes more image and description as aspect ratio is not look great

2023-06-24 09:52 UTC, anmode commented on components/Internship.js
> +
revert this if not needed!

2023-06-24 09:52 UTC, anmode commented on package.json
> +    "@nextui-org/react": "^1.0.0-beta.13",
revert this!

2023-06-24 09:52 UTC, anmode commented on public/assets/css/style.css
> +  text-overflow: ellipsis;
move all css of internship card in a css file named intership-section
and please update css names from courses -> internship
we can have css file in `styles` folder

2023-06-26 09:42 UTC, closed without merging