feat: add important meta elements to improve seo 🚀
anmode/grabtern-frontend pull request #513
Opened 2023-07-13 14:16 UTC by 0xabdulkhalid

## Related Issue

Closes: #501 

## Description of Changes
- This PR is about adding important meta elements for improving the site's seo score along to boost site's vital performance
- Meta elements in HTML play a crucial role in providing information about the webpage to browsers and search engines. 
- They are typically placed in the head section of an HTML document and are not displayed directly on the webpage.
- Those Meta elements in HTML serve various purposes, including defining document encoding, improving search engine visibility, enhancing social media sharing, optimizing for mobile devices, and influencing browser behavior. 
- Utilizing appropriate meta elements can significantly impact how webpages are perceived, indexed, and shared on the internet.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

2023-07-13 15:48 UTC, anmode commented
errors are there.. try to build locally
```


./pages/_app.page.js:68:8
--
19:46:54.050 | Syntax error: Unexpected token
19:46:54.050 |  
19:46:54.050 | 66 \|         />
19:46:54.050 | 67 \|
19:46:54.050 | > 68 \|        <!-- SEO ESSENTIALS -->
19:46:54.050 | \|         ^
19:46:54.050 | 69 \|         <meta
19:46:54.050 | 70 \|             name="robots"
19:46:54.050 | 71 \|             content="index, follow"


```

2023-07-14 01:04 UTC, 0xabdulkhalid commented
Sorry for the inconvience, i will make those changes after evening.

Cuz, I'm way to my college.

2023-07-14 02:56 UTC, anmode commented
> Sorry for the inconvience, i will make those changes after evening.
> 
> Cuz, I'm way to my college.

no worries, when you get time carry on :)

2023-07-16 03:29 UTC, 0xabdulkhalid commented
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> Name 	Status 	Preview 	Comments 	Updated (UTC)
> **grabtern-frontend** 	white_check_mark Ready ([Inspect](https://vercel.com/anmode/grabtern-frontend/AEtd1bw19NmvEACE2uTC1kK3aZyL)) 	[Visit Preview](https://vercel.live/open-feedback/grabtern-frontend-git-fork-0xabdulkhalid-closes-i-cd2bfd-anmode.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 	speech_balloon [**Add feedback**](https://vercel.live/open-feedback/grabtern-frontend-git-fork-0xabdulkhalid-closes-i-cd2bfd-anmode.vercel.app?via=pr-comment-feedback-link) 	Jul 16, 2023 3:26am

@anmode Now's the Build has been successfully deployed!

2023-07-16 03:30 UTC, 0xabdulkhalid commented
Hey there @anmode, now you can check the Build.

There's no error now.

2023-07-16 18:11 UTC, anmode commented
Sure!!

2023-07-17 07:02 UTC, maaz-bin-asad requested changes

2023-07-17 07:02 UTC, maaz-bin-asad commented on pages/_app.page.js
> +            content="With GrabTern you can easly get your dream Intern from GSoc, MLH, Amazon ML Summer Intern and Many more that will be guide by mentor only just for ₹ 1 Rupee, So What are you wait
Spelling mistakes and reframing the content to make it more appealing.

2023-07-17 07:02 UTC, maaz-bin-asad commented on pages/_app.page.js
> +            content="With GrabTern you can easly get your dream Intern from GSoc, MLH, Amazon ML Summer Intern and Many more that will be guide by mentor only just for ₹ 1 Rupee, So What are you wait
Same here. Check the content again

2023-07-17 07:02 UTC, maaz-bin-asad commented on pages/_app.page.js
> +            content="Intern, Internships, GSoc, MLH, Amazon ML Summer Intern, Outreachy, GrabTern, Internship, Adobe SHE Codes"
Add "Mentor" related keywords. Besides, keywords should always be specific

2023-07-19 04:25 UTC, Abhinavcode13 commented
@0xabdulkhalid Are you working?

2023-07-20 12:49 UTC, 0xabdulkhalid commented
Yeah, I'm here @Abhinavcode13.

2023-07-20 12:50 UTC, 0xabdulkhalid commented
I just busy due to attending my college, i will continue this work tonight.

2023-07-21 01:45 UTC, 0xabdulkhalid commented
Hey there @maaz-bin-asad, i have resolved those changes you need.

Now you can verify them once again.

2023-07-21 07:54 UTC, 0xabdulkhalid commented
> Can we have other SEO improvements in this pR only? I have tested with some SEO tools. Grabtern needs to improve SEO. Please look into it.

I can't get your thoughts about "other SEO", i think this PR is enough for SEO Improvements.

Because i have covered every important meta elements to meet the right aspects for SEO.

2023-07-21 08:03 UTC, 0xabdulkhalid commented
Can i know why the deployment's UI is differ from the default grabtern UI ?

2023-07-21 10:33 UTC, maaz-bin-asad approved these changes

2023-07-21 10:33 UTC, maaz-bin-asad commented
> Hey there @maaz-bin-asad, i have resolved those changes you need.
> 
> Now you can verify them once again.

Approved

2023-07-22 07:06 UTC, anmode commented
> > Can we have other SEO improvements in this pR only? I have tested with some SEO tools. Grabtern needs to improve SEO. Please look into it.
> 
> I can't get your thoughts about "other SEO", i think this PR is enough for SEO Improvements.
> 
> Because i have covered every important meta elements to meet the right aspects for SEO.
> 
> **EDIT**: Now i can get your words @anmode, the SEO is affected due to non-crawlable links and images without proper `alt` attributes. We can make another issue and related PR for that. For now this PR is for adding Meta.
 

yess, ok you can cover them in other PR.
and actually deployment UI will be new UI for grabtern.. I'll soon put it into production after some bug fixes and improvment.
so think like deployment version is new release for grabtern.

2023-07-22 07:06 UTC, anmode commented
> > Hey there @maaz-bin-asad, i have resolved those changes you need.
> > Now you can verify them once again.
> 
> Approved

Thanks @maaz-bin-asad bhaiya :)

2023-07-22 07:07 UTC, anmode commented
@0xabdulkhalid Prettier test is failing.. please fix it;
run `npx prettier --write .`

2023-07-22 11:36 UTC, 0xabdulkhalid commented
Everything's are perfectly wrapped up now 🚀 

@anmode now it's time to merge this PR.

2023-07-22 11:51 UTC, merged

2023-07-22 11:51 UTC, anmode commented
Cool, congrats.. Next PR would be level 3 for sure...

2023-07-22 17:21 UTC, 0xabdulkhalid commented
Oops @anmode, you have forget to add `level` label for this merged PR.

Please make sure to add that necessary label otherwiser GSSOC won't take this PR in account.

Hope you understood.

2023-07-26 02:34 UTC, anmode commented
sorry my bad! done