toggle form created
anmode/grabtern-frontend pull request #542
Opened 2023-07-17 19:50 UTC by ShreyaDhiman24

## Related Issue
#494 

Closes: #494 

## Description of Changes

[Screencast from 18-07-23 01:18:03 AM IST.webm](https://github.com/anmode/grabtern-frontend/assets/98320971/74821d6e-6baa-4413-b77f-34ae868d5ecc)

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.
- [ ] All of them
## Screenshots

2023-07-18 02:09 UTC, anmode requested changes
The functionality left, on submit API are different for the mentor as well as for the user too.
this case applies to google login too.

Mobile optimization is also left

2023-07-18 02:09 UTC, anmode commented on pages/mentorLogin.page.js
> +      <div className="login-form d-flex flex-column bg-white tw-mb-10">
To remove white space, modify padding in the `login-form` class

2023-07-20 08:51 UTC, anmode commented
@ShreyaDhiman24 ?

2023-07-20 20:20 UTC, ShreyaDhiman24 commented
@anmode I have fixed all the issues that were there in the css..you can checkout..!

2023-07-21 03:51 UTC, anmode commented
cool@

2023-07-21 03:51 UTC, merged