Register page
anmode/grabtern-frontend pull request #550
Opened 2023-07-19 17:33 UTC by shraddha761

## Related Issue

Closes: #440 

## Description of Changes

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![Original screenshot](link) | ![Updated screenshot](link) |

Please provide any necessary screenshots to illustrate the changes made.

2023-07-19 17:34 UTC, shraddha761 commented
@anmode please review

2023-07-20 01:21 UTC, anmode commented
I did not like the designing... Please see: https://github.com/anmode/grabtern-frontend/pull/542
and the register page is not optimized for mobile too

2023-07-20 03:11 UTC, shraddha761 commented
@anmode Yahh IK Design is not so good now

2023-07-20 11:51 UTC, shraddha761 commented
@anmode please review now

2023-07-21 03:56 UTC, anmode commented
Cool, Some fixes:
1. Please use UI button as register button is of old UI, you can see components/ui/button
2. optimize mobile view, reduce side padding as form looking so compact and a `or` line extending the form ( a bug)

2023-07-21 06:31 UTC, anmode commented
kch changes kiye... @shraddha761 please update your branch with develop

2023-07-21 15:36 UTC, shraddha761 commented
@anmode Hn maine kre

2023-07-21 16:06 UTC, anmode commented
please fix the test:
```
./components/layout/Header.js:14:9
Syntax error: Identifier 'ButtonLink' has already been declared.

  12 | import clsx from "clsx";
  13 | import { encryptData, decryptData } from "../../hook/encryptDecrypt";
> 14 | import { ButtonLink } from "../UI";
     |          ^
  15 |
  16 | function Header() {
  17 |   const {


```

2023-07-21 16:27 UTC, anmode reviewed
simple

2023-07-21 16:27 UTC, anmode commented on components/layout/Header.js
> +import { ButtonLink } from "../UI";
remove it

2023-07-21 16:59 UTC, anmode commented
`npx prettier --write .`

2023-07-21 17:02 UTC, anmode commented
<img width="530" alt="Screenshot 2023-07-21 at 10 30 45 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/8fca4508-233e-40e9-9461-45c381765d8a">
 
please reduce the padding.

2023-07-21 17:51 UTC, anmode commented
<img width="753" alt="Screenshot 2023-07-21 at 11 21 02 PM" src="https://github.com/anmode/grabtern-frontend/assets/88332977/cdabc211-4807-44c0-b36a-842aa8431630">
text align :(

2023-07-21 17:52 UTC, anmode requested changes
last

2023-07-21 17:52 UTC, anmode commented on components/layout/Header.js
> +              <ButtonLink text="Sign Up" href="/register" />
revert please it is `auth/register` only

2023-07-21 18:33 UTC, shraddha761 commented
@anmode done with changes

2023-07-22 06:45 UTC, anmode approved these changes
Perfect! Congrats.

2023-07-22 06:46 UTC, merged

2023-07-22 06:46 UTC, shraddha761 commented
> Perfect! Congrats.

thank you