fix: moved community section to different page
anmode/grabtern-frontend pull request #593
Opened 2023-07-24 15:13 UTC by harmeetsingh11

## Related Issue

Closes: #540 

## Description of Changes

Moved Grabtern section to a different page called community.

### Files modified
- `components/layout/Header.js`
- `pages/index.page.js`

### Files added
- `components/Community/CommunityCard.jsx`
- `pages/community.page.js`

## Screenshots
[GrabTern-Grab-Your-Internship.webm](https://github.com/anmode/grabtern-frontend/assets/130365071/46f33f3c-b78b-492f-b83f-0d62a4c0aa60)

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] My changes have not introduced any new warnings.

@anmode please review this PR.
Thanks

2023-07-25 01:55 UTC, Isha988 requested changes

2023-07-25 01:55 UTC, Isha988 commented on components/Community/CommunityCard.jsx
> +import { ProfileCard, IconLink } from "../UI";
@harmeetsingh11 Remove unused imports `IconLink`, `RiLinkedinLine`, `RiTwitterLine`

2023-07-25 01:55 UTC, Isha988 commented on pages/index.page.js
> -                {...teamsOptions}
Also remove this` teamsOptions `object from `index.page.js`

2023-07-25 09:30 UTC, Isha988 approved these changes
Looks good to me 👍

2023-07-26 02:58 UTC, merged

2023-07-26 03:11 UTC, harmeetsingh11 commented
@anmode thanks for merging the PR. Can you please add `level` label to it?

2023-07-27 00:43 UTC, anmode commented
Sorrry! My bad added now